# This is a basic workflow to help you get started with Actions

name: CI
on:
  pull_request:
    branches:
      - main
    types:
      - closed

# Later, in the jobs section of your actions.yml file.
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl https://example.com/
